import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/ui";
import { Suspense } from "react";
import { MainShell } from "@/components/layout";
import Header from "@/components/Header";
import HeaderSkeleton from "@/components/HeaderSkeleton";
import ServiceWorkerRegister from "@/components/ServiceWorkerRegister";
import { ServiceWorkerProvider } from "@/components/performance";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ThemeProvider>
          <MainShell>
            <Suspense fallback={<HeaderSkeleton />}>
              <Header />
            </Suspense>
            {children}
          </MainShell>
          <ServiceWorkerRegister />
          <ServiceWorkerProvider />
        </ThemeProvider>
      </body>
    </html>
  );
}
